### ISSUE TITLE
text Validation inside disabled toggle group

### ISSUE THREAD

**Issue by Elaci0** [MikePohatu/TsGui#10]
Hi there,
 could you help me to try to solve this problem please?
 I am trying to configure IP settings from inside TsGui. It works but I am trying to "beautify" the appearance: each time I toggle/enable the group that contains all those textboxes, each with its own validation rule, the error message is triggered because I used  "ValidateEmpty=TRUE", which though is needed because I don't want empty values
The problem also is that I cannot disable the group unless I click four times the checkbox to enable/disable it.

Thanks!
[Config_IPvalidation.xml.txt](https://github.com/MikePohatu/TsGui/files/6886760/Config_IPvalidation.xml.txt)

**Comment by MikePohatu** [comment]
Righto, think I've found the issue. I set an option on the popup that is capturing the mouse which becomes more of an issue with multiple popups open at once. Just need to do a bit more tweaking and testing and will get a new version out

**Comment by MikePohatu** [comment]
Fixed in release 1.5.1.1 on website now
