### ISSUE TITLE
Reading available apps from task sequences

### ISSUE THREAD

**Issue by Elaci0** [MikePohatu/TsGui#12]
We have some apps we would like to install via task sequences. They are already defined into a nested task and upon request, we can remove or increase the  list. 
My question is if there is a easy/nice way to retrieves such list and build kind of checkboxes-tree  (even no tree) at run time into TsGui, otherwise it would be a pain to make changes each time a software is add/deleted from the task sequence.

thanks!

**Comment by MikePohatu** [comment]
I don't know about 'easy', but you could query the task sequence with the applications and build the appropriate XML using PowerShell. There is a script here: https://github.com/MikePohatu/TsGui/blob/master/Utilities/Create-Prestart-TS-List.ps1 that I used to create a pre-boot 'Select task sequence' type  dropdown list. 

I can't see this being added to TsGui any time soon if at all, but will keep it in the wish list

**Comment by Elaci0** [comment]
Nice! Thanks for the reply. Also I am sorry to have not looked too much in deep inside the sources!
