### ISSUE TITLE
ADK 22H2 Issues

### ISSUE THREAD

**Issue by harris1m** [MikePohatu/TsGui#15]
Having issues with TSGui loading in WinPE since upgrading to ADK 22H2, has anyone else experienced issues?

Error in status messages is:

The task sequence execution engine aborted execution for a failure of the action (Load Build Menu - WinPE) in the group (). The operating system reported error 2147956401: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail. 

Powershell and HTA are added as options to the boot image.

I have tried copying the UIAutomationCore.dll from previous working boot image. But not resolved.

**Comment by harris1m** [comment]
I have resolved. With ADK 22H2 i had to inject the configmgr cabs into the boot image before adding into SCCM otherwise WinPE would reboot just as it was loading. From advice from Microsoft, I had just injected the 4 main options. 

WinPE-WMI.cab
WinPE-Scripting.cab
WinPE-WDS-Tools.cab
WinPE-SecureStartup.cab

Once i injected NetFx and Powershell cabs into the clean boot wim. ONce added into SCCM, TSGUI now loads without error.

WinPE-NetFx.cab
WinPE-PowerShell.cab

At the time of writing why adding these optional components when editing the boot image in SCCM console did have the same result.

**Comment by MikePohatu** [comment]
Yeah that's a weird one. I'm using 22h2 with no problems or need to edit the boot wim directly. Note that you need HTA and NetFx, with PowerShell required if you're using that feature. You're first comment didn't mention NetFx, but I'm guessing that was a typo?

**Comment by harris1m** [comment]
Yes, an odd one for sure. Could just be my environment, my test setup is currently down so cannot confirm.
