### ISSUE TITLE
Entered value to populate another field

### ISSUE THREAD

**Issue by OlivierCNAF** [MikePohatu/TsGui#18]
Hello,

Thank you very much for TsGui which is a powerful tool.

Is it possible to use an entered value to populate another field?

For example, I would like all the values ​​entered on a page to be displayed as a summary on the next page.

We use TsGui_2.0.1.0

Thank you in advance for your feedback.

**Comment by MikePohatu** [comment]
Hi there, glad you're finding it useful :)

Yes this is doable using the option linking feature. Have a look at the documentation here: https://github.com/MikePohatu/TsGui/blob/master/documentation/features/OptionLinking.md

In your case you would add an ID to all your GuiOptions on the first page, then a bunch of InfoBox elements which use a LinkTo query to set the value. If you get stuck send me a message using the [contact page](https://www.20road.com/contact/) on the 20road.com website and I can help you out via email. 

Cheers,
Mike
