### ISSUE TITLE
Button Positioning in TsGui

### ISSUE THREAD

**Issue by dbanglad** [MikePohatu/TsGui#19]
Hello Everyone,
I am using Mike's TsGui and got stuck to position button. Could someone please help me with this. I want to move the button in the middle rather to the side

**Comment by MikePohatu** [comment]
Hi there, do you mean the Finish/Cancel buttons, or an action button? Finish/Cancel/Back currently don't have options to be moved.

**Comment by dbanglad** [comment]
Thank for u r reply. Yes, I was talking about the cancel/Finish button.
Mir
Sent from my iPhone

On Mar 12, 2024, at 8:37 PM, MikePohatu ***@***.***> wrote:

﻿

Hi there, do you mean the Finish/Cancel buttons, or an action button? Finish/Cancel/Back currently don't have options to be moved.

**Comment by MikePohatu** [comment]
OK will close this issue. Will have a look at some stage but I think it will be more work than its worth to support this one I'm afraid.
