### ISSUE TITLE
Failure during OSD in WinPE

### ISSUE THREAD

**Issue by act-GH** [MikePohatu/TsGui#2]
When calling the tsgui.exe from command line step in OSD task sequence, it causes the attached error in the smsts.log.

I replaced .exe with the most recent version 1.0.6.10 but still have the same result.

The boot.wim (currently OS v10.0.17763.1) does have .Netfx component installed. The boot.wim was recently updated from OS v10.0.14393.0 using the SCCM method for injecting a newer Windows ADK into the image. Ill try importing a new native 17763 version of the boot.wim as well as a 14393 version to see if that makes a difference.

TsGui.exe runs fine in Windows Test mode so it seems to be WinPE related.

[failure.log](https://github.com/MikePohatu/TsGui/files/3302342/failure.log)

**Comment by MikePohatu** [comment]
Hi there,

This is likely the known issue with WPF in WinPE. Have a look at these articles:

https://www.reddit.com/r/SCCM/comments/9me9vn/workaround_for_adk_1809_wpf_display_issue_replace/ 
https://www.imab.dk/workaround-fixing-crashing-wpf-forms-in-powershell-after-updating-to-windows-10-adk-v1809/ 

Let me know if that doesn't sort your issue.

Cheers,

Mike

**Comment by act-GH** [comment]
That worked, thanks much.
