### ISSUE TITLE
Unable to hide a page from a NoUIOption

### ISSUE THREAD

**Issue by jrblanchette** [MikePohatu/TsGui#20]
Hello,

First, I want to thank you for this wonderful tool. I've only recently started using TsGui but it is clearly very powerful and I'm excited to incorporate it into my SCCM task sequences.

I've hit a small issue though. I would like to hide or show a page depending on the value of a task sequence variable. I figured I could use a toggle inside a NoUIOption to achieve this. If I try to hide a GuiOption using this method, this works perfectly fine. For example, to hide a heading on page 2 unless the machine is a laptop:

```
<TsGui LiveData="TRUE" Output="ConfigMgr" PurgeInactive="TRUE">
	<Height>330</Height>
	<Width>550</Width>

	<HardwareEval />

	<Page>
		<Row>
			<Column>
				<GuiOption Type="Heading">				
					<Label>Page 1</Label>
					<Bold />
				</GuiOption>
			</Column>
		</Row>
	</Page>

	<Page>
		<Row>
			<Column>
				<GuiOption Type="Heading">
					<Group>Group_Hide</Group>
				
					<Label>Page 2</Label>
					<Bold />
				</GuiOption>
			</Column>
		</Row>
	</Page>
	
	<NoUI>
		<NoUIOption>
			<Variable>Toggle_Hide</Variable>
			<SetValue>
				<Query Type="EnvironmentVariable">
					<Variable Name="TsGui_IsLaptop" />
				</Query>
			</SetValue>
			
			<Toggle Group="Group_Hide">
				<Enabled>TRUE</Enabled>
				<Disabled>FALSE</Disabled>
				<Hide />
			</Toggle>
		</NoUIOption>
	</NoUI>
</TsGui>
```

However, if I move the group under the Page tag instead, I get an exception when running TsGui:

```
...
<Page>
	<Group>Group_Hide</Group>
	
	<Row>
		<Column>
			<GuiOption Type="Heading">
				<Label>Page 2</Label>
				<Bold />
			</GuiOption>
		</Column>
	</Row>
</Page>
...
```

![TsGui Exception](https://github.com/MikePohatu/TsGui/assets/166419634/5aa08fbd-206d-4fc2-b141-dfc2f1a4b40e)

I'm using the latest 2.0.22.0 version.

Thanks in advance!

**Comment by MikePohatu** [comment]
Fixed in 2.0.23.0 up on website now
