### ISSUE TITLE
TSGui Variable Typo

### ISSUE THREAD

**Issue by jolegape** [MikePohatu/TsGui#21]
Hi Mike

Was working on replicating my UI++ config into TSGui, and noticed the variable for the subnet mask shows as TSGui_IPSubetMask4.

![image](https://github.com/user-attachments/assets/2d8438bb-1135-403a-b34b-3ca7fd2ba6de)

Not a big issue. Just wanted to pass it along.

Gavin

**Comment by MikePohatu** [comment]
Thanks for the bug report. Will get that fixed.

**Comment by MikePohatu** [comment]
Typo fixed
