### ISSUE TITLE
Hide next page witch checked checkbox 

### ISSUE THREAD

**Issue by Sageza-84** [MikePohatu/TsGui#22]
Hi, i'm trying to hide my second page by default, i'm trying to use a Toggle group with a checkbox thats checked by default,
it works if i uncheck and recheck the checkbox, but its not hiding the second page when the checkbox (thats checked by default) is not touched.

The idea is if somebody unchecks it, only then it should display the second page.

```	
<Page>
	<Row>
		<Column>
			<GuiOption Type="CheckBox" InactiveValue="TRUE">
				<Variable>Apps_Common</Variable>
				<Checked/>
				<Label>Install common apps</Label>
				<Toggle Group="Group_Apps" Invert="TRUE">
					<Enabled>TRUE</Enabled>
					<Disabled>FALSE</Disabled>
					<Hide/>
				</Toggle>
			</GuiOption>
		</Column>
	</Row>
</Page>
<Page>
	<Group>Group_Apps</Group>
</Page>
```

**Comment by MikePohatu** [comment]
Looks like there is a problem in the Toggle initialisation code. Will get an update out as soon as I figure it out.

**Comment by MikePohatu** [comment]
No problem. New version is up on the website too.
