### ISSUE TITLE
Application not captured in Remote sessions.

### ISSUE THREAD

**Issue by Josch62** [MikePohatu/TsGui#4]
In Windows PE (typically ConfigMgr/MDT running ADK 2004) Controls with the property "AllowsTransparency"="True" fails being captured. The applicaton works perfectly well locally but is completely invisible in the Remote Control Window. As a test I flipped the property on the Main Window and the TsDropDownListUI.Control ComboBox, it then worked as expected. Not sure though which other, possibly negative, impact the changes could have?

**Comment by MikePohatu** [comment]
Thanks for the diagnostics. I actually had another support request regarding that so you saved me a bunch of time. I'm not aware of anything that would cause issues with setting that property so will try updating everything and do some testing.

**Comment by Josch62** [comment]
Brilliant; a few more pieces of information... The ComboBox doesn't expose the property, you need a custom control template, and set it on this part <Popup x:Name="PART_Popup" AllowsTransparency="False"..../> I also ran into some problems creating the template while on .Net 4.0 - a switch to 4.6.2 solved that issue.

**Comment by MikePohatu** [comment]
Cool thanks. I try to hold the .Net version back so it will work for people updating their OS from an older version. Will be interesting to see if I can make it go in .Net 4.0

**Comment by MikePohatu** [comment]
Fixes applied in the dev branch. So far working fine, but still needs a full test run and a couple of tweaks if I can figure them out

**Comment by MikePohatu** [comment]
Fixed now in 1.2.5.0. There were issues with the validation popups and dropdownlist which are now resolved. Has passed my tests.
