### ISSUE TITLE
Saving Active Directory credentials

### ISSUE THREAD

**Issue by Elaci0** [MikePohatu/TsGui#5]
Hi there!
 I see that AD credentials, once entered and verified, cannot be reused later by the task sequence, once TSgui is closed. 
 Do you think it would be possible to add an option to let me to choose whether to find such credentials later?
 
 Thanks,
 alessio

**Comment by MikePohatu** [comment]
Hi Alessio,

This was done this way on purpose for security reasons. I have had a few requests though so am looking at allowing this option. Will let you know but will probably be in the new year before this comes out.

Cheers,

Mike

**Comment by Elaci0** [comment]
Hi Mike,
 I understand your point. Almost :)
 I noticed some while ago that credentials saved into any task sequence's step, for joining the domain e.g., are anyhow visible doing a dump of the TS variables. So I felt somehow "authorized" to create my own script which, at the very beginning, asks for user's credentials, checked against AD and reused later to join the computer and other tasks; this way I could create a generic task sequence for all my collaborators without saving anything into the task sequence itself.

Of course, something already built in TSgui would help a lot, so I am happy I am not alone asking you such option to keep credentials reusable inside the task. No hurry though.

Thanks
alessio

**Comment by MikePohatu** [comment]
This is available as an option now. See doco [here](https://github.com/MikePohatu/TsGui/blob/master/documentation/options/PasswordBox.md)
