### ISSUE TITLE
Dropdown list and WMI queries with NULL results

### ISSUE THREAD

**Issue by Elaci0** [MikePohatu/TsGui#7]
Using a dropdown list I have not find a way to display a default text when the result of a WMI query is null. For example the following retrieves the partitions found in a disk, but sometimes the disk might be clean and no partitions are found:
```
<Query Type="Wmi">
	<Wql>select Index,DiskIndex,Size FROM Win32_DiskPartition WHERE DiskIndex=0</Wql>
	<NameSpace>root\CIMV2</NameSpace> <!-- Option to set the namespace -->
	<Property Name="Index">
		<Calculate>VALUE+1</Calculate>
	</Property>
	<Property Name="DiskIndex">
		<Prefix>Disk: </Prefix>
	</Property>
	<Property Name="Index">
		<Calculate>VALUE+1</Calculate>
		<Prefix>PartitionNumber: </Prefix>
	</Property>
	<Property Name="Size">
		<Calculate DecimalPlaces="2">VALUE/1073741824</Calculate>
		<Prefix></Prefix>
		<Append>GB</Append>
	</Property>
	<Separator>, </Separator>
</Query>
```

So if I am using a dropdown list I will not see anything (actually a very thin blank line) but a text "NO PARTITIONS FOUND" could be more helpful.
I tried with some   IFELSE queries but  I can only set a value to an optionValue and not a string

thanks
alessio

PS: I am sorry, these and other I will post, are not actually "Issues"  but I don't know how to submit feature requests

**Comment by MikePohatu** [comment]
Yep this is an issue. Technically this can probably be done with the current code, but it is horrible. I'm making some updates that will make this better. Will let you know when the new version is out and how to set it up

**Comment by MikePohatu** [comment]
OK, after faffing around I realised you can do this quite easily. Add a 'Combined' query below your WMI query like below. This first <Value> will become your variable value, the rest will be your text.

`<Query Type="Wmi">
...
</Query>
<Query Type="Combined">
    <Value>0</Value>
    <Value>No partition found</Value>
</Query>`

Let me know if that works.

**Comment by Elaci0** [comment]
Wow! I am quite sure to have tried almost everything but you know, there is always something you never thought..
It works! not in the way you suggested though (I always get an "no partition found"   option into the dropdown list) but you gave me a great hint! 
I modified the "diskcascade.xml" you sent me some time ago like this:
```
<GuiOption Type="DropDownList">
	<Group>Group_Disk0</Group>
	<Variable>OSDDiskPart</Variable>
	<Label>Partition</Label>
	<SetValue>
		<Value>0</Value>
	</SetValue>
	<Query Type="IfElse">
		<IF>
			<Source>
				<Query Type="Wmi">
					<Wql>select Index,DiskIndex,Size FROM Win32_DiskPartition WHERE DiskIndex=0</Wql>
					<NameSpace>root\CIMV2</NameSpace> <!-- Option to set the namespace -->
					<Property Name="Index"/>
				</Query>
			</Source>			
			<!-- Ruleset to compare the Source value against -->
			<Ruleset>
				<Rule Type="Equals">*NULL</Rule>
			</Ruleset>		
			<!-- The result to return if the ruleset matches -->
			<Result>
				<Query Type="Combined"> <Value>0</Value> <Value>No partition found</Value> </Query>
			</Result>
		</IF>
		<ELSE>
			<Query Type="Wmi">
				<Wql>select Index,DiskIndex,Size FROM Win32_DiskPartition WHERE DiskIndex=0</Wql>
				<NameSpace>root\CIMV2</NameSpace> <!-- Option to set the namespace -->
				<Property Name="Index"/>
				<Property Name="DiskIndex">
					<Prefix>Disk: </Prefix>
				</Property>
				<Property Name="Index">
					<Prefix>ID: </Prefix>
				</Property>
				<Property Name="Size">
					<Calculate DecimalPlaces="2">VALUE/1073741824</Calculate>
					<Prefix></Prefix>
					<Append>GB</Append>
				</Property>
				<Separator>, </Separator>
			</Query>
		</ELSE>
	</Query>
	<Validation ValidateEmpty="FALSE">
		<Message>Invalid partition selected!</Message>			
		<Valid>
			<Rule Type="LessThan">99</Rule>
		</Valid>
	</Validation>
</GuiOption>
```
..repeated for  N possible disks I have inside a system.
It works, but in the meanwhile I found another problem: the message "Invalid partition selected!"  does not disappear once the dropdown is unfocused (or toggled disabled).
Perhaps having an option to set a dropdown as "readonly" and not selectable could solve somehow the problem, but these are only beauties.

Again, thanks!
alessio

**Comment by MikePohatu** [comment]
Validation rules don't apply if the GuiOption is disabled by a toggle. Validation messages stay open and can be closed by the user in later versions.
