### ISSUE TITLE
Validation message persists after the GuiOption loose its focus

### ISSUE THREAD

**Issue by Elaci0** [MikePohatu/TsGui#8]
I have a series of GuiOptions toggled by a dropdown list. 
Each of them has a validation option and error-message which displays errors on wrong input and "Finish" button is disabled.
Though I found out that if a toggle-enabled GuiOption is triggered by an invalid input, the error message appears and stays there even if I toggle-disable the Gui-Option (which has wrong input but is not anymore on foreground)
In the latter case the Finish button is working.

Thanks,
 alessio

**Comment by MikePohatu** [comment]
Hi Alessio,

Can you email me you full config so I can test please?

Cheers,
Mike

**Comment by Elaci0** [comment]
I am attaching here the file.
For this test I run TSgui inside a virtual machine with an extra blank hard disk attached 
When you select a disk with some partitions everything works like expected except if you select the drive without any partitions: "No partition found" will be automatically selected and the invalid message appears. While here you cannot press the Finish button.
As soon as you go back to the drive with partitions you still have the error message, but you can press Finish now.


Thanks,
 Alessio
[Config_diskcascade.zip](https://github.com/MikePohatu/TsGui/files/5734146/Config_diskcascade.zip)

**Comment by MikePohatu** [comment]
Hi there,

I think I've found the issue. Expect an update in the next day or so. 

Also, I think you might be missing a PurgeInactive option. On the drop down lists that have the Group_DiskX set, add PurgeInactive="TRUE", for example

`<GuiOption Type="DropDownList" PurgeInactive="TRUE">
	<Group>Group_Disk1</Group>
	<Variable>OSDDiskPart</Variable>
`

This will make sure your options that are setting the same variable aren't conflicting with each other

**Comment by MikePohatu** [comment]
Version 1.2.5.2 available on the site now with a fix for this issue.
