### ISSUE TITLE
Question - Applications selection

### ISSUE THREAD

**Issue by meterien** [MikePohatu/TsGui#9]
Hi, i am experimenting with this toolkit to replace my old MDT wizard in my MECM task sequence. 
I have a question about my Applications selection list : 

Is this possible to create a variable ex : APP01 = 'APP_GUID' when i click a checkbox. So when i click 7-Zip by exemple a variable named APP01 is created with a value and i can use this variable in my task sequence.

Thanks!

**Comment by MikePohatu** [comment]
Hi there. Yes this is pretty much all TsGui does. It doesn't do anything special in the task sequence, it just creates task sequence variables. What you do with those variables is up to you. If you have a look at the intro video that is exactly what I do: https://youtu.be/C8CUHicY2fY?t=782

**Comment by meterien** [comment]
Thanks, yes i watch the video available on youtube it's very helping. 

I am now able to select my disk and format option, Active Directory Name, description et OU location to setup variable for my task sequence. It work fine thanks to your TsGui.

My next project is to replace the MDT Wizard applicaiton tree to be able to select individual app and app by parent profile or role.

It work, i am able to create on the fly the XML to populate checkbox (to display the name) and NoGui variable (to create OSDAPPS01 variable). We have too many app like 160.....I am able to get these variable onto my task sequence and it kind of work. I am trying to find a way to display many item but my solution feel kind of weird and take way to much space on screen.

I know treeview is not currently an option but have you any tips to display large number of item with your toolkit?

![image](https://user-images.githubusercontent.com/11343274/116874843-f8820e00-abe7-11eb-82e4-657764fbce1e.png)

**Comment by chewychewytoo** [comment]
I just started my testing of TSGUI, and I know this is an old thread. I think using groups and/or multiple pages would be ideal for that number of applications.

**Comment by meterien** [comment]
Thanks and yes multiple page was my solution after all. For m'y environment  i finally create a powershell script to generate multiple page for the application in fact it just generate the xml based on sccm application. The sets i dont think i used but if Seem a good Idea.
